/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Strategy } from "./Strategy";
import { StrategyCountArgs } from "./StrategyCountArgs";
import { StrategyFindManyArgs } from "./StrategyFindManyArgs";
import { StrategyFindUniqueArgs } from "./StrategyFindUniqueArgs";
import { CreateStrategyArgs } from "./CreateStrategyArgs";
import { UpdateStrategyArgs } from "./UpdateStrategyArgs";
import { DeleteStrategyArgs } from "./DeleteStrategyArgs";
import { BacktestResultFindManyArgs } from "../../backtestResult/base/BacktestResultFindManyArgs";
import { BacktestResult } from "../../backtestResult/base/BacktestResult";
import { StrategyService } from "../strategy.service";
@graphql.Resolver(() => Strategy)
export class StrategyResolverBase {
  constructor(protected readonly service: StrategyService) {}

  async _strategiesMeta(
    @graphql.Args() args: StrategyCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Strategy])
  async strategies(
    @graphql.Args() args: StrategyFindManyArgs
  ): Promise<Strategy[]> {
    return this.service.strategies(args);
  }

  @graphql.Query(() => Strategy, { nullable: true })
  async strategy(
    @graphql.Args() args: StrategyFindUniqueArgs
  ): Promise<Strategy | null> {
    const result = await this.service.strategy(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Strategy)
  async createStrategy(
    @graphql.Args() args: CreateStrategyArgs
  ): Promise<Strategy> {
    return await this.service.createStrategy({
      ...args,
      data: args.data,
    });
  }

  @graphql.Mutation(() => Strategy)
  async updateStrategy(
    @graphql.Args() args: UpdateStrategyArgs
  ): Promise<Strategy | null> {
    try {
      return await this.service.updateStrategy({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Strategy)
  async deleteStrategy(
    @graphql.Args() args: DeleteStrategyArgs
  ): Promise<Strategy | null> {
    try {
      return await this.service.deleteStrategy(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.ResolveField(() => [BacktestResult], { name: "backtestResults" })
  async findBacktestResults(
    @graphql.Parent() parent: Strategy,
    @graphql.Args() args: BacktestResultFindManyArgs
  ): Promise<BacktestResult[]> {
    const results = await this.service.findBacktestResults(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
